# Generated by Django 3.1 on 2020-09-09 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('unesco', '0002_auto_20200909_2126'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='States',
            new_name='State',
        ),
        migrations.RenameField(
            model_name='site',
            old_name='states',
            new_name='state',
        ),
    ]
